setwd("~/Documentos/Cursos/Curso de Data Sicence/Reproducible-research")
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", "data-activity.zip")
unzip("data-activity.zip", exdir = "DATA")
activity <- read.csv("./DATA/activity.csv", header = TRUE)
activity$date <- as.Date(as.character(activity$date), "%Y-%m-%d")
steps.pear.day <- tapply(activity$steps, activity$date, FUN = mean, na.rm = TRUE)
hist(steps.pear.day, main = "Histogram steps per day", xlab = "Steps per day", col = "green")
mean.perday <- mean(steps.pear.day, na.rm = TRUE)
meadian.perday <- median(steps.pear.day, na.rm = TRUE)